name: Automated E2E Testing
on:
  pull_request:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install all dependencies
        run: npm install

      - name: Start Vite server
        run: |
          npx vite --host &
          npx wait-on http://localhost:3000
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

      - name: Run Cypress Tests with Electron
        uses: cypress-io/github-action@v6
        with:
          browser: electron
        env:
          VITE_USER_EMAIL: ${{ secrets.VITE_USER_EMAIL }}
          VITE_USER_PASSWORD: ${{ secrets.VITE_USER_PASSWORD }}
